### ISSUE TITLE
/Applications/Xcode_8.3.3.app/Contents/Developer/usr/bin/xcodebuild test-without-building -xctestrun /usr/local/lib/ruby/gems/2.3.0/gems/run_loop-2.6.2/lib/run_loop/device_agent/ipa/DeviceAgent-Runner.app/PlugIns/DeviceAgent.xctest/DeviceAgent-device.xctestrun -destination id=f16583ed3a14aecb08183682c94aab67943ca08a -derivedDataPath /Users/radmin/.run-loop/DeviceAgent/DerivedData   :- This command giving below error for ios 10.2

### ISSUE THREAD

**Issue by ketan077** [calabash/calabash-ios#1353] opened 2017-11-21 16:53 UTC
2017-11-21 16:37:33.736 xcodebuild[58104:680648] DTDeviceKit: Could not start house arrest service for app identifier com.apple.test.DeviceAgent-Runner [Error Domain=com.apple.dtdevicekit Code=-402652996 "The requested application's data container path does not exist." UserInfo={NSLocalizedFailureReason=The requested application's data container path does not exist., com.apple.dtdevicekit.stacktrace=(

**Comment by jmoody** [comment] 2017-11-22 04:35
duplicate of #1350

Please do not post duplicate issue.

**Closed by jmoody** 2017-11-22 04:35 UTC
