### ISSUE TITLE
Simulator not found under Xcode 6.3 beta 2 using RESET_BETWEEN_SCENARIOS=1

### ISSUE THREAD

**Issue by danyalaytekin** [calabash/calabash-ios#724] opened 2015-03-10 17:33 UTC
## Environment

```
$ xcode-select -p
/Applications/Xcode-Beta.app/Contents/Developer

$ xcodebuild -version
Xcode 6.3
Build version 6D520o

$ calabash-ios version
0.13.0
```

## Problem

`cucumber` succeeds.
`RESET_BETWEEN_SCENARIOS=1 cucumber` fails.

Both commands succeed when `xcode-select` is set back to `/Applications/Xcode.app/Contents/Developer` (Xcode 6.1).

**Comment by JaniJegoroff** [comment] 2015-03-10 17:53
I see the same issue when using Xcode 6.2 (I will post some console traces soon).

**Comment by JaniJegoroff** [comment] 2015-03-10 18:03
**Environment**
```
Janis-iMac:Sushi-iOS janijegoroff$ xcode-select -p
/Applications/Xcode62/Xcode.app/Contents/Developer
Janis-iMac:Sushi-iOS janijegoroff$ xcodebuild -version
Xcode 6.2
Build version 6C131e
Janis-iMac:Sushi-iOS janijegoroff$ calabash-ios version
0.13.0
```

**Console traces**
```
Janis-iMac:myapp janijegoroff$ DEBUG_UNIX_CALLS=1 DEBUG=1 DEVICE_TARGET='iPad Retina (8.2 Simulator)' bundle exec cucumber --tags @test
Using the default, dev_ipad, sim_ipad_retina_82, reset, features, tags_default_ipad, tags_ci, tags_ipad and tags_skip_pending profiles...
@dev @ci @ipad @iphone
Feature: Developer launch menu view
  As a Developer
  I want to use developer launch menu
  So I can start testing different parts of the xxx application quickly

  @test
  Scenario: Test                  # Calabash/features/dev.feature:21
xcrun simctl list devices => stdout: '== Devices ==
-- iOS 8.1 --
    iPhone 6 Plus (12D50A35-95E3-422A-B861-839105F4950C) (Shutdown)
    iPhone 6 (4F4F7C82-1458-42A2-A626-12DDB2BA47AB) (Shutdown)
    iPad Retina (A3651BE5-F247-4476-83AA-E16135359A4B) (Shutdown)
-- iOS 8.2 --
    iPhone 4s (8AA4CBC7-58F3-4814-9BEA-5FE28EB293E2) (Shutdown)
    iPhone 5 (61EE02AA-7284-4345-B1BE-7B405D4265BE) (Shutdown)
    iPhone 5s (4A180A6B-454F-49F7-A076-71D9C1350B76) (Shutdown)
    iPhone 6 Plus (047E007E-41A3-4683-813C-06709A01BF34) (Shutdown)
    iPhone 6 (8405E87B-C398-4A5B-823B-1F663688E0E6) (Shutdown)
    iPad 2 (504C0D49-BDE9-404C-86CD-04F6871A0D6C) (Shutdown)
    iPad Retina (F137EB07-AB5B-453B-A451-EFD6F8D77585) (Shutdown)
    iPad Air (32BFB649-7731-4A0A-A583-76CC871948CB) (Shutdown)
    Resizable iPhone (AF93946E-721C-418B-9857-23C5EB3F0D7A) (Shutdown)
    Resizable iPad (EA066875-8C7F-4D46-A802-231C86EA4500) (Shutdown)
-- Unavailable: com.apple.CoreSimulator.SimRuntime.iOS-8-0 --
    iPhone 4s (6F5DC539-F7B2-42BF-9E7F-3119149C62DA) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5 (BC9B4819-4884-4926-9440-71DB31874F99) (Shutdown) (unavailable, runtime profile not found)
    iPhone 5s (AFF520E9-31C4-4827-8D48-79691EA8C4F0) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 Plus (30576415-6A17-46ED-AE57-7820E9B95659) (Shutdown) (unavailable, runtime profile not found)
    iPhone 6 (94BFA181-2D2E-4F6A-BA83-104C521631B8) (Shutdown) (unavailable, runtime profile not found)
    iPad 2 (F44485D0-FB71-49E2-926B-5F10A122624D) (Shutdown) (unavailable, runtime profile not found)
    iPad Retina (D43B7934-E723-4D3C-ADC1-8AED1BE56324) (Shutdown) (unavailable, runtime profile not found)
    iPad Air (E391CB8A-9C9F-445D-A459-D0F7DD949F66) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPhone (01E91D4C-43F7-4F0D-8E6F-6C02B5984D23) (Shutdown) (unavailable, runtime profile not found)
    Resizable iPad (AC9C9F05-B407-4BD8-99A4-EC721DCE0177) (Shutdown) (unavailable, runtime profile not found)' | stderr: ''
 Could not find simulator with udid 'D43B7934-E723-4D3C-ADC1-8AED1BE56324' (RuntimeError)
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:930:in `simctl_reset'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:213:in `reset_sim_content_and_settings'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:292:in `reset_app_sandbox'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:592:in `relaunch'
 /Users/janijegoroff/projects/myapp/Calabash/features/support/01_launch.rb:27:in `Before'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265))
Failing... Errno::ECONNREFUSED
 Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265) (Errno::ECONNREFUSED)
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `initialize'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `new'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `create_socket'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:747:in `block in connect'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `call'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:713:in `get'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:60:in `block in make_http_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:50:in `times'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:29:in `http'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/core.rb:139:in `server_version'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/environment_helpers.rb:192:in `_default_device_or_create'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/environment_helpers.rb:94:in `simulator?'
 /Users/janijegoroff/projects/myapp/Calabash/features/support/02_pre_stop_hooks.rb:5:in `Before'
    Given application is launched # cucumber-1.3.19/lib/cucumber/rb_support/rb_step_definition.rb:47

Failing Scenarios:
cucumber -p dev_ipad -p sim_ipad_retina_82 -p reset -p features -p tags_default_ipad -p tags_ci -p tags_ipad -p tags_skip_pending Calabash/features/dev.feature:21 # Scenario: Test

1 scenario (1 failed)
1 step (1 skipped)
0m1.717s
```

**Comment by danyalaytekin** [comment] 2015-03-10 18:04
Some progress: after installing the 8.1 simulators, the following command works:

`DEVICE_TARGET="iPhone 6 (8.1 Simulator)" RESET_BETWEEN_SCENARIOS=1 cucumber`

**Comment by jmoody** [comment] 2015-03-10 20:22
Well, it is a beta. :)

The problem is likely in run-loop, which has not been updated for Xcode 6.3 beta 2.

There are two problems:

1. Xcode 6.3 beta 2 named its app Xcode-beta.app not Xcode-**B**eta.app which means the beta detection algorithm probably cannot detect the Automation tracetemplate.  For whatever reason, Apple has been changing the location on a per-beta basis.
2. **SimControl is not filtering by "(unavailable, runtime profile not found)" causing failing builds when Xcode betas are installed** [run-loop #137](https://github.com/calabash/run_loop/issues/137)

I want to mention this, because it is often forgot.  Starting in Xcode 6, you must restart your machine after you install a new version of Xcode 6 _and_ after you install a new iOS Simulator SDK.

**Comment by jmoody** [comment] 2015-03-10 20:24
@danyalaytekin  I liked the use of the `ß`, but to make searching the issues easier, I changed the title to use `beta`.

**Comment by JaniJegoroff** [comment] 2015-03-10 20:27
@jmoody - I see this issue with official `Xcode 6.2`

**Comment by jmoody** [comment] 2015-03-10 23:50
@JaniJegoroff I think it might be #2 that mentioned above.

I am not having this problem locally.

**Comment by JaniJegoroff** [comment] 2015-03-11 00:18
I deleted all unavailable simulator runtimes using command `xcrun simctl delete <uid>` and rebooted machine.
```
Janis-iMac:~ janijegoroff$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
Resizable iPhone (com.apple.CoreSimulator.SimDeviceType.Resizable-iPhone)
Resizable iPad (com.apple.CoreSimulator.SimDeviceType.Resizable-iPad)
== Runtimes ==
iOS 8.1 (8.1 - 12B411) (com.apple.CoreSimulator.SimRuntime.iOS-8-1)
iOS 8.2 (8.2 - 12D508) (com.apple.CoreSimulator.SimRuntime.iOS-8-2)
== Devices ==
-- iOS 8.1 --
    iPhone 6 Plus (12D50A35-95E3-422A-B861-839105F4950C) (Shutdown)
    iPhone 6 (4F4F7C82-1458-42A2-A626-12DDB2BA47AB) (Shutdown)
    iPad Retina (A3651BE5-F247-4476-83AA-E16135359A4B) (Shutdown)
-- iOS 8.2 --
    iPhone 4s (8AA4CBC7-58F3-4814-9BEA-5FE28EB293E2) (Shutdown)
    iPhone 5 (61EE02AA-7284-4345-B1BE-7B405D4265BE) (Shutdown)
    iPhone 5s (4A180A6B-454F-49F7-A076-71D9C1350B76) (Shutdown)
    iPhone 6 Plus (047E007E-41A3-4683-813C-06709A01BF34) (Shutdown)
    iPhone 6 (8405E87B-C398-4A5B-823B-1F663688E0E6) (Shutdown)
    iPad 2 (504C0D49-BDE9-404C-86CD-04F6871A0D6C) (Shutdown)
    iPad Retina (F137EB07-AB5B-453B-A451-EFD6F8D77585) (Shutdown)
    iPad Air (32BFB649-7731-4A0A-A583-76CC871948CB) (Shutdown)
    Resizable iPhone (AF93946E-721C-418B-9857-23C5EB3F0D7A) (Shutdown)
    Resizable iPad (EA066875-8C7F-4D46-A802-231C86EA4500) (Shutdown)
Janis-iMac:~ janijegoroff$
```

Now getting following error:
```
Janis-iMac:Sushi-iOS janijegoroff$ DEBUG_UNIX_CALLS=1 DEBUG=1 DEVICE_TARGET='iPad Retina (8.2 Simulator)' bundle exec cucumber --tags @test
Using the default, dev_ipad, sim_ipad_retina_82, reset, features, tags_default_ipad, tags_ci, tags_ipad and tags_skip_pending profiles...
@dev @ci @ipad @iphone
Feature: Developer launch menu view
  As a Developer
  I want to use developer launch menu
  So I can start testing different parts of the xxx application quickly

  @test
  Scenario: Test                  # Calabash/features/dev.feature:21
xcrun simctl list devices => stdout: '== Devices ==
-- iOS 8.1 --
    iPhone 6 Plus (12D50A35-95E3-422A-B861-839105F4950C) (Shutdown)
    iPhone 6 (4F4F7C82-1458-42A2-A626-12DDB2BA47AB) (Shutdown)
    iPad Retina (A3651BE5-F247-4476-83AA-E16135359A4B) (Shutdown)
-- iOS 8.2 --
    iPhone 4s (8AA4CBC7-58F3-4814-9BEA-5FE28EB293E2) (Shutdown)
    iPhone 5 (61EE02AA-7284-4345-B1BE-7B405D4265BE) (Shutdown)
    iPhone 5s (4A180A6B-454F-49F7-A076-71D9C1350B76) (Shutdown)
    iPhone 6 Plus (047E007E-41A3-4683-813C-06709A01BF34) (Shutdown)
    iPhone 6 (8405E87B-C398-4A5B-823B-1F663688E0E6) (Shutdown)
    iPad 2 (504C0D49-BDE9-404C-86CD-04F6871A0D6C) (Shutdown)
    iPad Retina (F137EB07-AB5B-453B-A451-EFD6F8D77585) (Shutdown)
    iPad Air (32BFB649-7731-4A0A-A583-76CC871948CB) (Shutdown)
    Resizable iPhone (AF93946E-721C-418B-9857-23C5EB3F0D7A) (Shutdown)
    Resizable iPad (EA066875-8C7F-4D46-A802-231C86EA4500) (Shutdown)' | stderr: ''
 undefined local variable or method `cmd' for #<RunLoop::SimControl:0x007fd0bc5c9ba0> (NameError)
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:913:in `block (2 levels) in simctl_reset'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open3.rb:199:in `popen_run'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/open3.rb:93:in `popen3'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:909:in `block in simctl_reset'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:928:in `call'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:928:in `simctl_reset'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/run_loop-1.2.8/lib/run_loop/sim_control.rb:213:in `reset_sim_content_and_settings'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:292:in `reset_app_sandbox'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/launcher.rb:592:in `relaunch'
 /Users/janijegoroff/projects/Sushi-iOS/Calabash/features/support/01_launch.rb:27:in `Before'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265))
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265))
Failing... Errno::ECONNREFUSED
 Connection refused - connect(2) for "localhost" port 37265 (http://localhost:37265) (Errno::ECONNREFUSED)
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `initialize'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `new'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:799:in `create_socket'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:747:in `block in connect'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `call'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:612:in `query'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:164:in `query'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1191:in `do_get_block'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `block in do_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:713:in `get'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:60:in `block in make_http_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:50:in `times'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:50:in `make_http_request'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/http_helpers.rb:29:in `http'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/connection_helpers.rb:11:in `http'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/core.rb:139:in `server_version'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/environment_helpers.rb:192:in `_default_device_or_create'
 /Users/janijegoroff/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/calabash-cucumber-0.13.0/lib/calabash-cucumber/environment_helpers.rb:94:in `simulator?'
 /Users/janijegoroff/projects/Sushi-iOS/Calabash/features/support/02_pre_stop_hooks.rb:5:in `Before'
    Given application is launched # cucumber-1.3.19/lib/cucumber/rb_support/rb_step_definition.rb:47

Failing Scenarios:
cucumber -p dev_ipad -p sim_ipad_retina_82 -p reset -p features -p tags_default_ipad -p tags_ci -p tags_ipad -p tags_skip_pending Calabash/features/dev.feature:21 # Scenario: Test

1 scenario (1 failed)
```

**Comment by jmoody** [comment] 2015-03-11 00:29
@JaniJegoroff 

Remove the `DEBUG_UNIX_CALLS` - looks like this revert commit was not good enough:  **Revert 'logger' changes in sim_control.rb** [run_loop/f37c2d](https://github.com/calabash/run_loop/commit/f37c2fd1b79fbe0068d4537a8e0a340bf3e2a440).

FYI/BTW - DEBUG_UNIX_CALLS will be deprecated or marked private in a future release.

**Comment by JaniJegoroff** [comment] 2015-03-11 00:37
@jmoody - Ah, I see. I was just using `DEBUG_UNIX_CALLS` for debugging this specific issue. Works like a charm now. :+1:

**Comment by jmoody** [comment] 2015-03-16 12:48
**UPDATE**

Starting in Xcode 6.2, instruments cannot launch simulators with UDID _if_ the simulator SDK < 8.0.

**Comment by jmoody** [comment] 2015-04-09 17:04
**UPDATE**

Starting in Xcode 6.3, you _can_ launch simulators with UDID for any supported simulator SDK.

The iOS 7.0.3 SDK is _not_ supported on Yosemite; it might be installed, but Apple has stated it will not launch.

**Comment by jmoody** [comment] 2015-04-09 17:04
I am going to close this issue.  If it appears again in Xcode 6.3, please update the title and reopen.

**Closed by jmoody** 2015-04-09 17:04 UTC
