### ISSUE TITLE
touch gesture timing out on Xcode 7.2.1 simulators 

### ISSUE THREAD

**Issue by ankurgamit** [calabash/calabash-ios#1094] opened 2016-05-05 13:45 UTC
Environment:
Xcode 7.2.1
calabash-cucumber 0.19.0
run_loop 2.1.1
cucumber 2.3.3
OSX Yosemite 10.10.5

Simulators tried: 
iPhone 6 (8.4)
iPhone 6 (9.2)
iPhone 5s (8.4)
iPhone 5s (9.0)

Device tried:
iPhone 6 plus (8.1.2)

On running tests with RESET_BETWEEN_SCENARIOS=1, 
On simulator - test runs fine on first screen, scrolls fine and touches button but on second screen screen, it does touches the button for first time but on second time it times out with below:

RuntimeError: uia action failed because: Timed out running command uia.tapOffset('{:x 351, :y 41}')

Looks like, app gets stuck on this particular screen and even touching button manually, nothing happens. 
However, on running the app manually on xcode, works fine with and without calabash target.

On device - on first screen, scrolling is fine it fails touching the button.

On monitoring simulator logs, got this at the tail:
 DEBUG LPUIAUserPrefsChannel:101 | response current index: 5

Not sure, if the problem is in the app or calabash. Tried few things with iOS developer for this particular screen to be able to make it work. But test run is failing on this particular screen and it doesn't seems to be issue with the app.

**Comment by jmoody** [comment] 2016-05-05 14:02
Possible duplicate of **Can't touch UIButton on iPhone 5c** #1090

I believe that the the problem is that the correct default strategy is not being selected automatically.

@ankurgamit, @NarKasH please try:

```
options = {
  :uia_strategy => :host
}

launcher.relaunch(options)
```

### Related

* **is the default strategy :host for iOS 9 devices?** [#450](https://github.com/calabash/run_loop/issues/450)

**Comment by ankurgamit** [comment] 2016-05-05 14:13
Hi @jmoody, 

Thanks for quick response.

Tried your suggestion in launch.rb, but no joy. 
Still experiencing same whilst running tests

**Comment by jmoody** [comment] 2016-05-05 14:20
Please check the simulators log. You can tail the simulator logs with:

```
# After the simulator has launched
$ bundle exec run-loop simctl tail
```

Look for:

1. DEBUG LPUIAUserPrefsChannel: - should not see any PrefChannel activity
2. A large amount of NSLog activity: [Hot Topic](https://github.com/calabash/calabash-ios/wiki/Hot-Topics#2-nslog-output-can-cause-apps-to-become-unresponsive-during-testing) before the failed touch.

Also run with `DEBUG=1` and visually verify that strategy is `:host`.

**Comment by ankurgamit** [comment] 2016-05-05 15:45
Hi @jmoody 

1. DEBUG LPUIAUserPrefsChannel - not seeing any PrefChannel activity
2. Not a large amount of NSLog output.
However this is what I'm getting in simulator logs:

```
May  5 16:22:33  ***securityd[45708]:  SecTaskCopyAccessGroups No keychain access group specified whilst running in simulator, falling back to default set
May  5 16:22:35 --- last message repeated 1 time ---
May  5 16:22:35 ***[45737]: DEBUG LPMapRoute:134 | Map POST, /map Parsed UIScript as
	(
	    "view:'UIButton'",
	    "with marked:'mybuttonlabel1'"
	)
May  5 16:22:35 ***mstreamd[45686]: (Note ) PS: Media stream daemon stopping.
May  5 16:22:35 *** mstreamd[45686]: (Note ) AS: <MSIOSAlbumSharingDaemon: 0x7fd04a508e50>: Shared Streams daemon has shut down.
May  5 16:22:35 *** mstreamd[45686]: (Warn ) mstreamd: mstreamd shutting down.
May  5 16:22:38 ***[45737]: DEBUG LPMapRoute:134 | Map POST, /map Parsed UIScript as
	(
	    "view:'UILabel'",
	    "with marked:'mylabel"
	)
May  5 16:22:40 ***[45737]: DEBUG LPMapRoute:134 | Map POST, /map Parsed UIScript as
	(
	    "view:'UIButton'",
	    "with marked:'mybuttonlabel1'"
	)
May  5 16:22:41*** securityd[45708]:  SecTaskCopyAccessGroups No keychain access group specified whilst running in simulator, falling back to default set
May  5 16:22:41 *** assertiond[45698]: assertion failed: 14F1713 12H141: assertiond + 12334 [EDAF3958-87C7-3C61-A8E6-24689FBBE168]: 0x1
May  5 16:22:41 *** securityd[45708]:  SecTaskCopyAccessGroups No keychain access group specified whilst running in simulator, falling back to default set
May  5 16:22:41 --- last message repeated 1 time ---
May  5 16:22:41 ***[45737]: Google Maps SDK for iOS version: 1.10.17867.0
May  5 16:22:41 ***[45737]: New version of Google Maps SDK for iOS available: 1.13.24379.0
May  5 16:22:41 *** assertiond[45698]: assertion failed: 14F1713 12H141: assertiond + 12334 [EDAF3958-87C7-3C61-A8E6-24689FBBE168]: 0x1
May  5 16:22:42 --- last message repeated 2 times ---
May  5 16:22:42 *** securityd[45708]:  SecTaskCopyAccessGroups No keychain access group specified whilst running in simulator, falling back to default set
May  5 16:22:42 --- last message repeated 2 times ---
May  5 16:22:42 *** com.apple.CoreSimulator.SimDevice.656B97DA-EF03-4EC2-87B0-37843EBDA54C.launchd_sim[45680] (com.apple.imfoundation.IMRemoteURLConnectionAgent): The _DirtyJetsamMemoryLimit key is not available on this platform.
May  5 16:22:42 *** kbd[46041]: table drop: 101
May  5 16:22:42 *** bird[46045]: starting bird
May  5 16:22:43 *** bird[46045]: Unable to bootstrap_check_in() to namedDelegatePort 'com.apple.bird.push'. APS connections will not persist past process lifetime.
May  5 16:22:43 *** bird[46045]: Power level really becomes good
May  5 16:22:43 *** bird[46045]: Network reachability changed to reachable [-R -------]
May  5 16:22:43 ***[45737]: DEBUG LPMapRoute:134 | Map POST, /map Parsed UIScript as
	(
	    "view:'UINavigationButton'",
	    "with marked:'Close'"
	)
May  5 16:22:45 ***[45737]: DEBUG LPMapRoute:134 | Map POST, /map Parsed UIScript as
	(
	    "view:'UILabel'",
	    "with marked:'mylabel"
```

On simulator launches, initially strategy is shown :preferences, then sim launches again and strategy is shown :host

```
2016-05-05 15:49:13 +0100 [RunLoop:debug]: 
{
                  :app => #<APP myapp 1.0 /Users//Documents/projects/myapp.app>,
                 :args => [],
            :bundle_id => "mybundleid",
               :device => #<Simulator: iPhone 6 (8.4) 656B97DA-EF03-4EC2-87B0-37843EBDA54C x86_64>,
         :inject_dylib => nil,
          :instruments => #<Instruments 7.2.1>,
             :log_file => "/Users/.run-loop/results/2016-05-05_15-48-51/run_loop.out",
          :results_dir => "/Users/.run-loop/results/2016-05-05_15-48-51",
    :results_dir_trace => "/Users/.run-loop/results/2016-05-05_15-48-51/trace",
               :script => "/Users/.run-loop/results/2016-05-05_15-48-51/_run_loop.js",
               :simctl => #<Simctl: 7.2.1>,
                 :udid => "656B97DA-EF03-4EC2-87B0-37843EBDA54C",
         :uia_strategy => :preferences,
                :xcode => "7.2.1",
           :xcode_path => "/Applications/Xcode.app/Contents/Developer"

```
```
2016-05-05 15:50:03 +0100 [RunLoop:debug]: 
{
                  :app => #<APP myapp 1.0 /Users/Documents/projects/myappl-cal.app>,
                 :args => [],
            :bundle_id => "mybundleid",
               :device => #<Simulator: iPhone 6 (8.4) 656B97DA-EF03-4EC2-87B0-37843EBDA54C x86_64>,
         :inject_dylib => nil,
          :instruments => #<Instruments 7.2.1>,
             :log_file => "/Users/.run-loop/results/2016-05-05_15-49-46/run_loop.out",
          :results_dir => "/Users/.run-loop/results/2016-05-05_15-49-46",
    :results_dir_trace => "/Users/.run-loop/results/2016-05-05_15-49-46/trace",
               :script => "/Users/.run-loop/results/2016-05-05_15-49-46/_run_loop.js",
               :simctl => #<Simctl: 7.2.1>,
                 :udid => "656B97DA-EF03-4EC2-87B0-37843EBDA54C",
         :uia_strategy => :host,
                :xcode => "7.2.1",
           :xcode_path => "/Applications/Xcode.app/Contents/Developer"
}
```

**Comment by jmoody** [comment] 2016-05-05 16:09
If you are seeing :preferences at all,  please check your hooks.

**Comment by ankurgamit** [comment] 2016-05-05 16:48
my hooks.rb is empty.

**Comment by jmoody** [comment] 2016-05-16 10:11
There is a bug in the latest run-loop.

Please add this to your launch options:

```
options => { :uia_strategy => :host }
```

**Comment by jmoody** [comment] 2016-05-17 05:04
Fixed in run-loop develop branch.  Will be part of run-loop 2.1.2.

**Closed by jmoody** 2016-05-17 05:04 UTC

**Comment by mvemjsun** [comment] 2016-06-13 12:33
@ankurgamit does using run-loop 2.1.2 fix the issue for you? I seem to be getting a similar issue with calabash 0.19.1 on simulator(various devices, using run-loop 2.1.3). Touches work until I reach a screen where it does not seem to have any effect ```touch ("view:'MPMovieView' button marked:'playerDoneButton'")```
