### ISSUE TITLE
Latest framework version crashes when calling backdoor

### ISSUE THREAD

**Issue by Neil3079** [calabash/calabash-ios#890] opened 2015-10-27 13:14 UTC
Upon updating our project to the latest framework version everytime a back door method is called the app crashes with the following stack trace

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSInvocation _invocationWithMethodSignature:frame:]: method signature argument cannot be nil'
*** First throw call stack:
(
	0   CoreFoundation                      0x062b6a84 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x05caae02 objc_exception_throw + 50
	2   CoreFoundation                      0x06162a32 +[NSInvocation _invocationWithMethodSignature:frame:] + 386
	3   CoreFoundation                      0x061628a0 +[NSInvocation invocationWithMethodSignature:] + 48
	4   MS3-cal                             0x000f7fd2 -[LPBackdoorRoute JSONResponseForMethod:URI:data:] + 1650
	5   MS3-cal                             0x000d79fa -[LPRouter httpResponseOnMainThreadForMethod:URI:] + 1962
	6   MS3-cal                             0x000d7fa9 __38-[LPRouter httpResponseForMethod:URI:]_block_invoke + 89
	7   libdispatch.dylib                   0x06cf89cd _dispatch_client_callout + 14
	8   libdispatch.dylib                   0x06cdfda4 _dispatch_barrier_sync_f_slow_invoke + 133
	9   libdispatch.dylib                   0x06cf89cd _dispatch_client_callout + 14
	10  libdispatch.dylib                   0x06cddf90 _dispatch_main_queue_callback_4CF + 910
	11  CoreFoundation                      0x062085fe __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	12  CoreFoundation                      0x061c62f4 __CFRunLoopRun + 2356
	13  CoreFoundation                      0x061c5706 CFRunLoopRunSpecific + 470
	14  CoreFoundation                      0x061c551b CFRunLoopRunInMode + 123
	15  GraphicsServices                    0x07f7f664 GSEventRunModal + 192
	16  GraphicsServices                    0x07f7f4a1 GSEventRun + 104
	17  UIKit                               0x036421eb UIApplicationMain + 160
	18  MS3-cal                             0x004a81bc main + 140
	19  libdyld.dylib                       0x06d22a21 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by Neil3079** [comment] 2015-10-27 13:17
update last working version was 14.3

**Comment by jmoody** [comment] 2015-10-27 13:34
Looks like a duplicate of https://github.com/calabash/calabash-ios/issues/885

Let's close this and I will @mention you with questions in that issue.

**Closed** 2015-10-27 16:09 UTC
Labels: duplicate
