### ISSUE TITLE
Error while trying to install Calabash-Sandbox.

### ISSUE THREAD

**Issue by subinrevi** [calabash/calabash-ios#1036] opened 2016-03-18 06:34 UTC
Attaching the screenshot of the terminal. Running the following command.

When running "calabash-iso gen" command not found error is shown.

curl -sSL https://raw.githubusercontent.com/calabash/install/master/install-osx.sh | bash
![screen shot 2016-03-17 at 5 29 02 pm](https://cloud.githubusercontent.com/assets/8567369/13870113/7b4e9f70-ed01-11e5-8121-1ae28093aa7a.png)

**Comment by jmoody** [comment] 2016-04-16 08:11
Duplicate of **Getting an error while trying to install Calabash.** [#50](https://github.com/calabash/install/issues/50)

**Closed by jmoody** 2016-04-16 08:11 UTC
