### ISSUE TITLE
Calabash cannot relaunch the simulator ios version 9.0 

### ISSUE THREAD

**Issue by harikavegi1991** [calabash/calabash-ios#838] opened 2015-09-13 16:12 UTC
Hi there,

I have just updated my Xcode to Version 7.0. And I am running my app in Simulator version 9.0 (Because our app needs to work on iOS 9.0).
I could set up the calabash properly but start_test_server_in_background in calabash-ios console is erroring with the following log:

Unable to start. Make sure you've set APP_BUNDLE_PATH to a build supported by this simulator version
Calabash::Cucumber::Launcher::StartError: Calabash::Cucumber::Launcher::StartError: Time out waiting for UIAutomation run-loop execution expired. 
 Logfile /var/folders/zb/hg8f4m1n2qjc4mhvpn6tk5nm0000gp/T/run_loop20150913-15113-1i2l0i0/run_loop.out 

 Known Devices:
LON0092 [FC9E1E63-271C-54C9-93E3-91F31FB522BB]
iPad 2 (9.0) [C834085A-437B-4BDD-88B0-FCF264ECE7DA]
iPad Air (9.0) [3DACAE1B-7299-4450-97B8-7A69CD6FD09C]
iPad Air 2 (9.0) [2158A071-745A-4F14-BB7B-C1DD7B7B7AD0]
iPad Retina (9.0) [9B1EDA0E-D962-4B1A-9DF5-30E83B70DBA0]
iPhone 4s (9.0) [8B22D111-FA8D-4336-9365-F980686536BF]
iPhone 5 (9.0) [0C197967-179B-44C7-BA50-510D5130D951]
iPhone 5s (9.0) [A610C27F-A610-40DE-BD0E-B0037E304FFA]
iPhone 6 (9.0) [FA96253F-3F56-4B02-AB4C-2490CF7236A0]
iPhone 6 (9.0) + Apple Watch - 38mm (2.0) [C98C57F9-AC94-4442-B24F-1F37524885ED]
iPhone 6 Plus (9.0) [77076DCD-BACD-4BBE-8974-AA8F8D0A99A4]
iPhone 6 Plus (9.0) + Apple Watch - 42mm (2.0) [A3FE1C48-02DD-4D3F-BBFB-718E1CE991B4]
iPhone 6s (9.0) [8AAFB893-928F-4FA9-BA7E-1D07C3AEE582]
iPhone 6s Plus (9.0) [D2CFE5CE-C32E-4635-9897-14F6EF790AD8]

	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:766:in `new_run_loop'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:631:in `relaunch'
	from /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:883:in `start_test_server_in_background'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'

With reference to the reporting problem checklist:
>xcode-select --print-path
/Applications/Xcode.app/Contents/Developer

>xcodebuild -version
Xcode 7.0
Build version 7A218

>calabash-ios version
0.14.3
>curl http://localhost:37265/version
curl: (7) Failed to connect to localhost port 37265: Connection refused

The same error occurs when I am trying to run my calabash tests.

Any help would be much appreciated.

**Comment by jmoody** [comment] 2015-09-14 03:24
Calabash has not been updated to fully support Xcode 7's iOS 9 Simulators.  The simulator environment is still unstable, even in the GM released last week.  This is the same story as the previous two years.  I have two suggestions:

1. Keep your run-loop version up to date.
2. Use the :host or :shared_element strategy (vs the default :preferences).

**Comment by ark-konopacki** [comment] 2015-09-14 07:26
I'm able to run tests on iOS 9.0 simulator with Xcode 7 GM using :host strategy 
with calabash 0.14.3 and run_loop 1.5.1 without any issue 
@harikavegi1991 please check what you have build your app on same target as you use with calabash

**Comment by jmoody** [comment] 2015-09-14 07:28
@ark-konopacki Thanks for the independent verification.

> please check what you have build your app on same target as you use with calabash

I just released run-loop 1.5.2 which will detect stale apps on the simulator and reinstall them.  Hurray!

**Comment by harikavegi1991** [comment] 2015-09-14 09:02
Thank you so much for the response @jmoody and @ark-konopacki , I will try to update run-loop and see if that resolves the issue.

**Comment by harikavegi1991** [comment] 2015-09-14 15:00
@jmoody and @ark-konopacki  I have updated my run_loop to 1.5.2 and it worked. Thank you so much for the suggestions.

**Comment by harikavegi1991** [comment] 2015-09-14 15:04
Except that I am getting some warnings.
FYI,

WARN: deprecated '1.5.0' - Replaced with RunLoop::Xcode
/Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.2/lib/run_loop/xctools.rb:183:in `xcode_version_gte_51?'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:490:in `default_launch_method'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:420:in `default_launch_args'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:534:in `relaunch'
/Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:883:in `start_test_server_in_background'

**Comment by jmoody** [comment] 2015-09-16 17:29
@harikavegi1991 Suppressed that output in run-loop 1.5.4 (just released).  Thanks for reporting!

**Comment by carmbruster** [comment] 2015-09-22 20:10
I had this same issue and followed the suggestions but I am now getting this error when I type start_test_server_in_background.
version information:
calabash-cucumber (0.14.3, 0.14.0)
run_loop (1.5.4, 1.4.1, 1.3.1)
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
Xcode 7.0
Build version 7A220

Update launch.rb with:
  launch_options = {:uia_strategy => :shared_element}
    @calabash_launcher.relaunch(launch_options)


Error received:
 > calabash-ios console
Running irb...
irb(main):001:0> start_test_server_in_background
RunLoop::Xcrun::XcrunError: execution expired
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:55:in `rescue in exec'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:72:in `exec'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/device.rb:275:in `simulator_data_dir_size'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/device.rb:301:in `simulator_wait_for_stable_state'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/life_cycle/core_simulator.rb:99:in `launch_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/core.rb:214:in `prepare_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/core.rb:310:in `run_with_options'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop.rb:106:in `run'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:755:in `block in new_run_loop'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:753:in `times'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:753:in `new_run_loop'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/launcher.rb:631:in `relaunch'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.14.3/lib/calabash-cucumber/core.rb:883:in `start_test_server_in_background'
	from (irb):1
	from /Users/admin/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

Any help would be appreciated!  Thanks!

**Comment by jmoody** [comment] 2015-09-22 21:17
> calabash-cucumber (0.14.3, 0.14.0)

The minimum supported version for Xcode 7 is 0.16.3

https://github.com/calabash/calabash-ios/wiki/Updating-your-Calabash-iOS-version

**Comment by carmbruster** [comment] 2015-09-23 14:07
Hello - Thanks for the reply.  I upgraded to calabash-cucumber to 0.16.3 and upgraded the calabash.framework and I received the same messages as above.  When I upgraded the calabash.framework, the latest version looks like 0.16.2 so I removed 0.16.3 calabash and installed 0.16.2 calabash.  Cleaned build etc. based on the instructions you provided and I get the same error messages:

RunLoop::Xcrun::XcrunError: execution expired
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:55:in `rescue in exec'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:72:in `exec'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/device.rb:275:in `simulator_data_dir_size'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/device.rb:301:in `simulator_wait_for_stable_state'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/life_cycle/core_simulator.rb:99:in `launch_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/core.rb:214:in `prepare_simulator'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop/core.rb:310:in `run_with_options'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/run_loop-1.5.4/lib/run_loop.rb:106:in `run'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/launcher.rb:765:in `times'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
	from /Users/admin/.rvm/gems/ruby-2.2.1/gems/calabash-cucumber-0.16.2/lib/calabash-cucumber/core.rb:921:in `start_test_server_in_background'
	from (irb):1
	from /Users/admin/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'

**Comment by jmoody** [comment] 2015-09-23 14:28
Looks like a duplicate of **Default timeout in instruments.rb causes failure on slow hardware** [#259](https://github.com/calabash/run_loop/issues/259).

I will try to get a run-loop release out today.

**Comment by ark-konopacki** [comment] 2015-09-23 15:58
@carmbruster don't you have some permission popup in your app? I have similar situation when system popup shows before run_loop receive response from server in app. I mean it looks like that if i add some delay for that popup all goes smoothly. @jmoody can you check that behavior?

**Comment by jmoody** [comment] 2015-09-23 16:12
@ark-konopacki Can you provide a screenshot of the a privacy alert you are seeing?

We try to auto-dismiss the privacy alerts, but it a slow process of hunt-and-peck.  We can't find all the localized text the alerts which means we can't detect and dismiss them.

With that said, if a privacy alert pops _before_ instruments can take control of the app, then there is no way to interact with the app.

https://github.com/calabash/calabash-ios/wiki/Managing-Privacy-Alerts%3A--Location-Services%2C-APNS%2C-Contacts

**Comment by ark-konopacki** [comment] 2015-09-23 16:32
@jmoody thanks, but text is the first thing i was check and it looks ok. And if we cannot operate with that message it will be always not time to time. It looks for me like you say: privacy alert pops before instruments take control of the app, and it is appears mostly on slower mac's.

**Comment by ark-konopacki** [comment] 2015-09-23 18:32
@jmoody sorry for mess in my comments i have diff error with popups it's like:
```
2015-09-23 14:00:37 +0200 [RunLoop:debug]: xcrun instruments -w 3F12D209-374B-4F4E-8B62-0702613F409B -D /var/folders/63/g0clb5t92q50lgpvhq82kcn80000gn/T/run_loop20150923-50586-1w8bi9s/trace -t Automation /Users/dol/Library/Developer/Xcode/DerivedData/Aplication_Name.app -e UIARESULTSPATH /var/folders/63/g0clb5t92q50lgpvhq82kcn80000gn/T/run_loop20150923-50586-1w8bi9s -e UIASCRIPT /var/folders/63/g0clb5t92q50lgpvhq82kcn80000gn/T/run_loop20150923-50586-1w8bi9s/_run_loop.js >& /var/folders/63/g0clb5t92q50lgpvhq82kcn80000gn/T/run_loop20150923-50586-1w8bi9s/run_loop.out
2015-09-23 14:00:37 +0200 [RunLoop:debug]: Preparation took 3.564604 seconds
2015-09-23 14:01:07 +0200 [RunLoop:debug]: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
2015-09-23 14:01:07 +0200 [RunLoop:debug]: Failed to launch. Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError: Error while writing to fifo. RunLoop::Fifo::NoReaderConfiguredError
```
and after run_loop reach :launch_retries i get 
```
execution expired (RunLoop::Xcrun::XcrunError)
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:55:in `rescue in exec'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/xcrun.rb:72:in `exec'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/instruments.rb:137:in `block in templates'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/instruments.rb:152:in `call'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/instruments.rb:152:in `templates'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/core.rb:749:in `default_tracetemplate'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/core.rb:731:in `automation_template'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop/core.rb:315:in `run_with_options'
  /Library/Ruby/Gems/2.0.0/gems/run_loop-1.5.4/lib/run_loop.rb:106:in `run'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:767:in `block in new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:765:in `times'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:765:in `new_run_loop'
  /Library/Ruby/Gems/2.0.0/gems/calabash-cucumber-0.16.3/lib/calabash-cucumber/launcher.rb:635:in `relaunch'
  /Users/dol/Repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:101:in `launch_app'
  /Users/dol/Repos/heresuite-ios/UITests/cucumber/features/support/01_launch.rb:33:in `Before'
Retrying.. Errno::ECONNREFUSED: (Connection refused - connect(2)
```
but as i say in previous comment it appears only on slow mac's with hdd

**Comment by jmoody** [comment] 2015-09-23 19:37
@ark-konopacki The timeout for Xcrun.exec will be increased to 30s in the next version of run-loop.

**Increase the default timeout for Xcrun.exec** [#268](https://github.com/calabash/run_loop/pull/268)

**Comment by carmbruster** [comment] 2015-09-24 17:45
Do you have a time-frame for the release of the next version of run-loop?

**Comment by jmoody** [comment] 2015-09-24 18:17
@carmbruster Soon.  It is my top priority at the moment.

**Comment by carmbruster** [comment] 2015-09-28 14:47
Thanks @jmoody.  It's working again.

**Closed** 2015-09-28 14:49 UTC

**Comment by carmbruster** [comment] 2015-09-28 18:32
I was able to get the simulator to respond to start_test_server_in_background.  However, when I try to run my automated tests, I get a timeout on xcrun.  Is there a way to increase the timeout on that?
 
 Xcrun timed out after 30.12 seconds executing 'xcrun du -m -d 0 /Users/admin/Library/Developer/CoreSimulator/Devices/4777FE82-FB2D-4CCA-AFF7-D36A28F73D0F/data' with a timeout of 30 (RunLoop::Xcrun::TimeoutError)

**Comment by jmoody** [comment] 2015-10-01 09:35
@carmbruster 

Tracking your issue here: 

**Device#simulator_data_dir_size is timing out** [#287](https://github.com/calabash/run_loop/issues/287)

There is no way to increase the timeout.  It has been requested, but I haven't seen a case yet where the problem can't be solved with better programming (on my part).

In this case `du` is blocking and will probably hang indefinitely.
