### ISSUE TITLE
some queries cause the calabash 0.12.2 server to crash

### ISSUE THREAD

**Issue by marchv** [calabash/calabash-ios#690] opened 2015-01-27 13:46 UTC
Hi there :)

When I add an UISlider anywhere in my Swift-based project then app crashes when doing `query("slider")` in the Calabash console.

I am using:

        Calabash iOS server version: CALABASH VERSION: 0.12.0

When I then add this code somewhere in a Swift-based project:

        view.addSubview(UISlider())

And type below in the `calabash-ios console`:

        query("slider")

I get below crash in the app:

        #3	0x00147d3d in +[LPJSONUtils jsonifyView:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:170
        #4	0x00147293 in +[LPJSONUtils jsonifyObject:fullDump:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:92
        #5	0x00146fac in +[LPJSONUtils jsonifyObject:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:80
        #6	0x00121696 in -[LPQueryAllOperation performWithTarget:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m:66
        #7	0x00124489 in -[LPQueryOperation performWithTarget:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Operations/LPQueryOperation.m:17
        #8	0x00130156 in -[LPMapRoute applyOperation:toViews:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Routes/LPMapRoute.m:61
        #9	0x00130510 in -[LPMapRoute JSONResponseForMethod:URI:data:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Routes/LPMapRoute.m:95
        #10	0x00120e79 in -[LPRouter httpResponseForMethod:URI:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/LPRouter.m:118
        #11	0x0010c7e0 in -[LPHTTPConnection replyToHTTPRequest] at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaHttpServer/LPHTTPConnection.m:991
        #12	0x00111639 in -[LPHTTPConnection socket:didReadData:withTag:] at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaHttpServer/LPHTTPConnection.m:2336
        #13	0x00103679 in __39-[LPGCDAsyncSocket completeCurrentRead]_block_invoke at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaAsyncSocket/GCDAsyncSocket.m:4502
        #14	0x03e5830a in _dispatch_call_block_and_release ()

I could not find any similar reported around :s

Any known workarounds? Thanks!

**Comment by jmoody** [comment] 2015-01-27 17:35
Thanks @marchv.

I am curious about the `#1` and `#2` in the stack trace.  Can you update your post with those two lines?

It looks like there is a problem with calling `selected` on UISlider despite the fact that UISlider responds to `selected`.

Can you upgrade to 0.12.2?  I don't think it will help, but I want to eliminate chasing down a bug that has already been fixed.

**Comment by marchv** [comment] 2015-01-27 20:39
Hi @jmoody  and thanks a lot for your quick response :)

I have updated to 0.12.2 and still got the problem. Below is the full stack trace:

    #0	0x02ea6f46 in CFRetain ()
    #1	0x02eea8d2 in -[__NSDictionaryM setObject:forKey:] ()
    #2	0x02f67210 in -[NSMutableDictionary setObject:forKeyedSubscript:] ()
    #3	0x0009c0fd in +[LPJSONUtils jsonifyView:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:170
    #4	0x0009b653 in +[LPJSONUtils jsonifyObject:fullDump:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:92
    #5	0x0009b36c in +[LPJSONUtils jsonifyObject:] at /Users/moody/git/calabash-ios-server/calabash/Classes/Utils/LPJSONUtils.m:80
    #6	0x00075a56 in -[LPQueryAllOperation performWithTarget:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Operations/LPQueryAllOperation.m:66
    #7	0x00078849 in -[LPQueryOperation performWithTarget:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Operations/LPQueryOperation.m:17
    #8	0x00084516 in -[LPMapRoute applyOperation:toViews:error:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Routes/LPMapRoute.m:61
    #9	0x000848d0 in -[LPMapRoute JSONResponseForMethod:URI:data:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/Routes/LPMapRoute.m:95
    #10	0x00075239 in -[LPRouter httpResponseForMethod:URI:] at /Users/moody/git/calabash-ios-server/calabash/Classes/FranklyServer/LPRouter.m:118
    #11	0x00060ba0 in -[LPHTTPConnection replyToHTTPRequest] at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaHttpServer/LPHTTPConnection.m:991
    #12	0x000659f9 in -[LPHTTPConnection socket:didReadData:withTag:] at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaHttpServer/LPHTTPConnection.m:2336
    #13	0x00057a39 in __39-[LPGCDAsyncSocket completeCurrentRead]_block_invoke at /Users/moody/git/calabash-ios-server/calabash/Classes/CocoaAsyncSocket/GCDAsyncSocket.m:4502
    #14	0x03dc130a in _dispatch_call_block_and_release ()

Thanks! :)

**Comment by jmoody** [comment] 2015-01-30 15:31
I reproduced.  Now the question is why is this happening.

**Comment by jmoody** [comment] 2015-02-03 11:12
Fix is in the pipe.

**Comment by marchv** [comment] 2015-02-03 12:32
Great work @jmoody! Thanks :)

**Comment by jmoody** [comment] 2015-02-10 14:39
Fixed 0.12.3.

**Closed by jmoody** 2015-02-10 14:39 UTC
Labels: bug, reproduced

**Comment by marchv** [comment] 2015-02-10 15:15
@jmoody Thanks a lot for the quick fix - you are a star :)
