### ISSUE TITLE
Failed to launch. Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8: Instruments failed to launch app:

### ISSUE THREAD

**Issue by toniomg** [calabash/calabash-ios#760] opened 2015-05-08 15:41 UTC
Failed to launch. Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8: Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8

I'm using:
Xcode 6.3
iOS 8.3
calabash 0.14 with run-loop 1.3.2

I'm running the tests using jenkins like this:
xctool -project MyApp.xcodeproj -scheme MyApp-cal -sdk iphonesimulator -configuration Debug build test CONFIGURATION_BUILD_DIR=.

#Run cucumber
export APP_BUNDLE_PATH=`pwd`"/MyApp.app"
DEBUG=1 cucumber

First time it runs it works fine, but usually next time it doesn't. I'm not 100% sure of this cause the behaviour is unexpected.

I read about people having the same issue and being fixed in 1.3.1, but not luck for me. anything I can add?

Also. when it works, I can see it retrying to open the simulator several times until it starts.

Another issue is that I need to reset the simulator or it won't install the latest version, it uses the previous one.

**Comment by jmoody** [comment] 2015-05-08 16:57
Duplicate of https://github.com/calabash/calabash-ios/issues/744

@toniomg The problem boils down to a weird bug / new behavior in Xcode 6.3 on iOS 8.3 Simulator.  If the app is installed on the simulator, instruments cannot launch the app.

There are more details here:  https://github.com/calabash/calabash-ios/wiki/Hot-Topics

Are you using bundler and a Gemfile?  Can you be absolutely sure that you are using run_loop 1.3.2?

**Comment by toniomg** [comment] 2015-05-11 09:15
I'm not using a bundler.

These are my versions:

calabash-ios version 
0.14.1

run-loop version
1.3.2

I don't want to use a bundler cause I don't want to put more files in my project.

Can I uninstall calabash and run-loop and install everything again? Just to be sure it't not clashing with old versions.

**Comment by EliseLebeau** [comment] 2015-05-13 20:46
I have the same error message.
*** Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8 ***
Xcode 6.3
calabash-ios 0.14.1  
runloop 1.3.2

One thing I noticed is that since we added Watch kit to our builds, the time it takes for the sim to start is obscenely long.  I see this error message when runloop exits before my app has a chance to start.  

Is there a way to increase the timout (like a LOT).  It can take 60 seconds for my app to launch my beast...

**Comment by jmoody** [comment] 2015-05-13 21:12
@EliseLebeau @toniomg 

The root of the problem is that in some situations, the Xcode 6.3.* instruments cannot launch apps that are already installed on the iOS Simulator.

We've determined that for most apps, if the app is installed _and_ the simulator is running, instruments can launch the app.

The only other thing you can do is to delete the app from simulator (and your data) before launching.  We didn't want delete the app automatically because, well, it takes a long time and would probably be the wrong thing to do in most cases.

We've had some success by substituting the path to the app with the bundle id of the app, but this has also been flakey.  This is a change that needs to be made in run-loop.

At the moment, our options are limited:

1. Revert to Xcode 6.2
2. Use the iOS 8.2 simulators - we have not test exhaustively, but these simulators appear to be well behaved.
3. Delete the app from the simulator between launches.  I can try to put together a patch that demonstrates how to do this with the `RunLoop::Simctl::Bridge.`.  A very expensive solution would be to call `RunLoop::SimControl.new.reset_sim_content_and_settings` before launching the app.
4. Report this problem to Apple.

The problem persists in Xcode 6.4 b2 - I haven't evaled beta 3 yet.

@toniomg

> I don't want to use a bundler cause I don't want to put more files in my project.

Not to be a jerk, but it will make your life and our (support) life easier if use bundler.

You can delete the unwanted run-loop versions like this:

```
$ gem uninstall run-loop
```

@EliseLebeau 

> Is there a way to increase the timeout (like a LOT). It can take 60 seconds for my app to launch my beast.

```
launch_options = {
  # How long to wait for instruments to install (if necessary) and launch the app
  # If the app is large, it is not atypical for the install and launch to take a long time.
  #
  # Can also be controlled with UIA_TIMEOUT
  # The default is 10 seconds.
  :uia_timeout => 10, 
}

launcher.relaunch(launch_options)
```

**Comment by EliseLebeau** [comment] 2015-05-13 22:22
Thanks for the UIA_TIMEOUT! 
Oh I thought you had check in a fix for the 6.3 "installed app" issue which is why I posted.  
I need to build with 6.3 but I can hunt down some 6.2 sims :)

**Comment by jmoody** [comment] 2015-05-13 22:23
> Oh I thought you had check in a fix for the 6.3 "installed app" issue which is why I posted.

I did make a same-day fix, but apparently it isn't working for everyone.

**Comment by jmoody** [comment] 2015-05-13 22:52
@EliseLebeau By the way.  Hey!  Long time no chat!  I hope everything is going well.

**Comment by toniomg** [comment] 2015-05-14 08:08
Updating all my gems seemed to fix the problem, weird because I checked several times the versions for run_loop and calabash and they were both right.

**Comment by EliseLebeau** [comment] 2015-05-14 19:25
@jmoody Yeah!  I'm living mostly in Jenkins now which means a lot of swearing... :)

Downgrading to Sim 6.2 solved my problem.  It was extremely bad timing on my part that 6.3 was the first time in many months that I tried to use a Sim on Jenkins.  That used to be very hard!

**Comment by EliseLebeau** [comment] 2015-05-20 20:26
@jmoody UIA_TIMEOUT does not work when used like this
UIA_TIMEOUT=60 BUNDLE_ID=xxx DEVICE_TARGET='iPad Air (8.2 Simulator)' cucumber
It still moves on after 30 seconds (look at the timestamps).  

2015-05-20 13:16:30 -0700 [RunLoop:debug]: xcrun instruments -w iPad Air (8.2 Simulator) -D /var/folders/w5/f6vyf1hj3t7_f37qgjww2hr8tt9t8t/T/run_loop20150520-21241-1lw036r/trace -t Automation /Users/builder/workspace/ios-ipad-health-signin-sim/app/build/Product/Debug-iPhone-iphonesimulator/eBay.app -e UIARESULTSPATH /var/folders/w5/f6vyf1hj3t7_f37qgjww2hr8tt9t8t/T/run_loop20150520-21241-1lw036r -e UIASCRIPT /var/folders/w5/f6vyf1hj3t7_f37qgjww2hr8tt9t8t/T/run_loop20150520-21241-1lw036r/_run_loop.js >& /var/folders/w5/f6vyf1hj3t7_f37qgjww2hr8tt9t8t/T/run_loop20150520-21241-1lw036r/run_loop.out
2015-05-20 13:16:30 -0700 [RunLoop:debug]: Preparation took 82.117868 seconds
2015-05-20 13:17:00 -0700 [RunLoop:debug]: Failed to launch. execution expired: execution expired

**Comment by EliseLebeau** [comment] 2015-05-20 20:34
To answer my own question, I found that you can set 
@calabash_launcher.relaunch({:timeout => 300}) 
in 01_launch.rb to set that variable.

**Closed** 2015-06-17 09:18 UTC
Labels: duplicate

**Comment by tejasv02** [comment] 2015-09-03 15:37
I have added small rescue statement which is like a work around for the problem
If App fails to launch and throws exceptions, I will reset the app and relaunch it.
This seems to be working fine on Xcode 6.4 - Version 6.4 (6E35b)

  begin
    unless launcher.calabash_no_launch?
    launcher.relaunch(launch_options)
    launcher.calabash_notify(self)
  end
  rescue
    sim_control = RunLoop::SimControl.new
    sim_control.reset_sim_content_and_settings
    launcher.relaunch(launch_options)
  end

**Comment by pfisher3** [comment] 2015-09-09 01:18
Hi, Ive been experiencing this issue for a while now, trying to troubleshoot before I posted. I know its set to closed but I would appreciate any help in Debugging. Some ways I have tried to fix has included:
- reset_content_and_settings in launch.rb after each scenario
- changing the Simulator from 8.4 to 8.3 and 8.2, currently at 8.3 
- adding reset launch tags to the failing scenario, which is usually the 1st
- setting timeout to 500, as launch can take a while
- and much more
I want these test to be reliable for our CI env as only one test seems to fails, which is usually due to launch failure. Im currently building a simulator, and it will fail to launch occasionally on the first tests, all other tests run, and the simulator is reset through each scenario as Ive verified with DEBUG=1. the Simulator DEBUG instruction set looks like this:
*** Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8 ***

[0m
2015-09-08 19:36:27 -0400 [RunLoop:debug]: Preparation took 1.434106 seconds
2015-09-08 19:36:42 -0400 [RunLoop:debug]: Failed to launch. Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8: Instruments failed to launch app: 'FBSOpenApplicationErrorDomain error 8
2015-09-08 19:36:44 -0400 [RunLoop:debug]: Simulator instruction set 'x86_64' is compatible with ["i386", "x86_64"]
Updating device state attempt 1 failed in '0.089666'; will retry in '0.1'
Updating device state attempt 2 failed in '0.263689'; will retry in '0.1'
Updating device state attempt 3 failed in '0.440139'; will retry in '0.1'
Updating device state attempt 4 failed in '0.615082'; will retry in '0.1'
Updating device state attempt 5 failed in '0.785775'; will retry in '0.1'
Updating device state attempt 6 failed in '0.9552'; will retry in '0.1'
Waited for 0.139497 seconds for 'iOS Simulator' to start.
Waited for 0.401445 seconds for 'SimulatorBridge' to start.
2015-09-08 19:36:47 -0400 [RunLoop:debug]: 
{
                        :app => "/Users/jenkinsmacmini/Library/Developer/Xcode/DerivedData/ToysRUs-exsivqtmrahowueohymunroqghvx/Build/Products/calabash-iphonesimulator/project.app",
                       :args => [],
    :bundle_dir_or_bundle_id => "/Users/jenkinsmacmini/Library/Developer/Xcode/DerivedData/ToysRUs-exsivqtmrahowueohymunroqghvx/Build/Products/calabash-iphonesimulator/project.app",
                  :bundle_id => "com.project.project",
                     :device => "iphone",
              :device_target => "iPhone 6 (8.3 Simulator)",
              :launch_method => :instruments,
             :launch_retries => 5,
                   :log_file => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/run_loop.out",
                  :no_launch => false,
                    :no_stop => true,
         :relaunch_simulator => true,
                      :reset => false,
                :results_dir => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0",
          :results_dir_trace => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/trace",
                     :script => "/var/folders/xk/qyqczkk12gb0_nxg7fg4dgfh0000gp/T/run_loop20150908-42544-1peyuz0/_run_loop.js",
                :sdk_version => nil,
                    :timeout => 500,
                       :udid => "iPhone 6 (8.3 Simulator)",
               :uia_strategy => :preferences,
                      :xcode => "6.3",
                 :xcode_path => "/Applications/Xcode.app/Contents/Developer"
-------------------------------
Build settings:
-workspace project.xcworkspace -scheme project-calabash -sdk iphonesimulator8.3 'ARCHS=i386 x86_64' 'VALID_ARCHS=i386 x86_64' ONLY_ACTIVE_ARCH=NO clean build

in Jenkins the runs executes as such
+ bundle exec calabash-ios sim reset
+ DEBUG=1
+ cucumber --tags '~@wip' --tags '~@manual'

Thanks in advance.
