### ISSUE TITLE
undefined method embed for #<Calabash::Cucumber::Map> (regardless #1083 marked as fixed)

### ISSUE THREAD

**Issue by filipjakubowski** [calabash/calabash-ios#1096] opened 2016-05-10 13:46 UTC
Guys - I have used recent develop build
`Using calabash-cucumber 0.19.0 from https://github.com/calabash/calabash-ios.git (at develop@b643900)`
But I got en error 
`Then I press the "SignUpButton" button                # calabash-cucumber-0.19.0/features/step_definitions/calabash_steps.rb:30`
`undefined method embed for #<Calabash::Cucumber::Map:0x00000102217cf0> (NoMethodError)`

Do you know how to help me?

**Comment by mhk69** [comment] 2016-05-10 19:03
Had the same issue - have you upgraded the server? The downloaded one from NuGet was 0.17 for me once I upgraded to 0.19 it worked without an issue.

**Comment by jmoody** [comment] 2016-05-11 06:15
Closing as a duplicate of #1083

**Closed by jmoody** 2016-05-11 06:15 UTC
