### ISSUE TITLE
Calabash generates incorrect json for multi-arg method invocations

### ISSUE THREAD

**Issue by sapieneptus** [calabash/calabash-ios#787] opened 2015-06-11 10:57 UTC
E.g., 

Suppose we intend to call `[myPickerView viewForRow:3 forComponent:3]`

We do:
`query("UIPickerView", :viewForRow => 3, :forComponent => 2)`

It should generate:
```
@{
    @"operation" =    @{
        @"arguments" =         @[
                       @{
                             @"forComponent" : @2
                        },
                        @{
                            @"viewForRow" : @3
                        }
            }
        ],
        @"method_name" : @"query"
    }
    @"query" : @"UIPickerView"
}
```

But this instead generates:

```
@{
    @"operation" =    @ {
        @"arguments" =         @[
                        @{
                @"forComponent" : @2,   
                @"viewForRow" : @3    //both params in the same dict, no bueno
            }
        ],
        @"method_name" : @"query"
    }
    @"query" : @"UIPickerView"
}
```

Which then ends up invoking
`[myPickerView forComponent:2]`

**Comment by jmoody** [comment] 2015-06-11 13:58
@sapieneptus 

Am I correct in assuming that this works?

```
query("UIPickerView", [{:viewForRow => 3, :forComponent => 2}])
```

Without thinking about it at all, I am not sure if want to support the form you are proposing.

We also have this feature of the query language:

```
query("UIPickerView", :delegate, [{pickerView:nil},{titleForRow:1},{forComponent:0}])
```

**Comment by sapieneptus** [comment] 2015-06-11 14:37
Running this:
`query("UIPickerView", [{:viewForRow => 3, :forComponent => 2}])`
Gives the same output (excuse llvm formatting): 

```
{
    arguments =     (
                (
                        {
                forComponent = 2;
                viewForRow = 3;
            }
        )
    );
    "method_name" = query;
}
```

**Comment by sapieneptus** [comment] 2015-06-11 14:57
It appears only this syntax works:
`query("UIPickerView", [{viewForRow:0},{forComponent:0}])`. Is that as intended?

**Comment by jmoody** [comment] 2015-06-17 07:30
That is as intended.  @sapieneptus I am going to close this, but please re-open if we need to re-think this.

**Closed by jmoody** 2015-06-17 07:30 UTC
